name = "ClosedLoopReachability"
uuid = "73c0b437-a350-4e9b-97ac-9adb151c271b"
version = "0.6.3"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ControllerFormats = "02ac4b2c-022a-44aa-84a5-ea45a5754bcc"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
NeuralNetworkReachability = "5de1e908-2f08-45bf-a571-ac88a54f7e7f"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"
ReachabilityBase = "379f33d0-9447-4353-bd03-d664070e549f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
CommonSolve = "0.1 - 0.2"
ControllerFormats = "0.1 - 0.2"
LazySets = "2.14, 3, 4, 5"
NeuralNetworkReachability = "0.1"
OrdinaryDiffEq = "6"
Parameters = "0.12"
ReachabilityAnalysis = "0.14.5 - 0.28"
ReachabilityBase = "0.2.1 - 0.3"
Reexport = "0.2, 1"
Requires = "0.5, 1"
julia = "1.6"

[extensions]
OrdinaryDiffEqExt = "OrdinaryDiffEq"

[extras]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[weakdeps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
